theme: jekyll-theme-minima
title: Spotify Project
description: Predicting the Perfect Playlist!
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
